spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
cloudinary:
  env: ${CLOUDINARY_ENV}
---
# local
spring:
  profiles: local
  datasource:
    driver-class-name: ${DRIVER_CLASSNAME}
    url: ${DB_HOSTNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com:
      sns:
        server: debug
    org.springframework.security: debug
---
# prod
spring:
  profiles: prod
  datasource:
    driver-class-name: ${DRIVER_CLASSNAME}
    url: ${DB_HOSTNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com:
      sns:
        server: debug
    org.springframework.security: debug