spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
---
spring:
  profiles: local
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com:
      sns:
        server: debug
---
# prod
spring:
  profiles: prod
  datasource:
    driver-class-name: ${DRIVER_CLASSNAME}
    url: ${DB_HOSTNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true

logging:
  level:
    com:
      sns:
        server: info