spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}


jwt:
  signKey: ${JWT_SIGN_KEY}
  issuer: taggre

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---
# prod
spring:
  profiles: prod
  datasource:
    driver-class-name: ${DRIVER_CLASSNAME}
    url: ${DB_HOSTNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com:
      sns:
        server: info