spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

---
spring:
  profiles: local
  datasource:
    driver-class-name: ${DRIVER_CLASSNAME}
    url: ${DB_HOSTNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    platform: org.hibernate.dialect.H2Dialect

#  h2:
#    console:
#      enabled: true
#      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com:
      sns:
        server: debug
    org.springframework.security: debug
# org.springframework.security
---
# prod
spring:
  profiles: prod
  datasource:
    driver-class-name: ${DRIVER_CLASSNAME}
    url: ${DB_HOSTNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com:
      sns:
        server: debug
    org.springframework.security: debug