spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
#  servlet:
#    multipart:
#      file-size-threshold: 1MB
#      max-file-size: 10MB
#      max-request-size: 10MB
---
# local
spring:
  profiles: local
  datasource:
    driver-class-name: ${DRIVER_CLASSNAME}
    url: ${DB_HOSTNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com:
      sns:
        server: debug
    org.springframework.security: debug

cloudinary:
  env: ${DB_HOSTNAME}
---
# prod
spring:
  profiles: prod
  datasource:
    driver-class-name: ${DRIVER_CLASSNAME}
    url: ${DB_HOSTNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com:
      sns:
        server: debug
    org.springframework.security: debug

cloudinary:
  env: ${DB_HOSTNAME}