spring:
  datasource:
    driver-class-name: ${DRIVER_CLASSNAME}
    url: ${DB_HOSTNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true

logging:
  level:
    com:
      sns:
        server: debug